### ISSUE TITLE
Refer to #5574

### ISSUE THREAD

**Issue by imyhxy** [imyhxy/nni#1]
https://github.com/microsoft/nni/issues/5574

```yaml
trialCommand: nvidia-smi && sleep 60
trialCodeDirectory: ../../../../
debug: True
searchSpace:
  Global.epochs:
    _type: choice
    _value: [ 40 ]
  Optimizer.lr.learning_rate:
    _type: uniform
    _value: [ 0.2 , 1.5 ]
  Optimizer.regularizer.coeff:
    _type: uniform
    _value: [ 0.00001, 0.00008 ]
  DataLoader.Train.sampler.batch_size:
    _type: choice
    _value: [ 256 ]
trialGpuNumber: 8
trialConcurrency: 1
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  gpuIndices: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
tunerGpuIndices: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
```

Same issue when setting `trialGpuNumber: 8`, but not `trialGpuNumber: 1 or 4`
